stages:
  - install-environment
  - build
  - test

setup-my-project:
  stage: install-environment
  script:
    - mkdir -p /go/src/27thisotope.ddns.net/mibzman/CourseCorrect-Student
    - cd /go/src/27thisotope.ddns.net/mibzman/CourseCorrect-Student
    - sudo add-apt-repository ppa:masterminds/glide && sudo apt-get update
    - sudo apt-get install glide

build-my-project:
  stage: build
  script:
    - glide install
    - go build

test-my-project:
  stage: test
  script:
    - cd CourseCorrect-Student
    - go test
