stages:
  - build
#  - test
  - deploy

services:
  - docker:dind

build-go:
  stage: build
  image: golang:1.7
  before_script:
      - curl https://glide.sh/get | sh
      - glide -v
      - glide install
  artifacts:
    paths:
       - CourseCorrect-Student
  script:
    - go build

build-angular:
  stage: build
  image: hoatle/angular-cli
  artifacts:
    paths:
       - frontend/
  script:
    - cd frontend/
    - npm install
    - npm start

#test-my-project:
#  stage: test
#  script:
#    - go test

deploy-project:
  stage: deploy
  before_script:
    - pwd
    - ls
    # do nothing to override the global one
  dependencies:
  - build-go
  - build-angular
  script:
    #- docker info
    - docker build -t coursecorrect .
    - docker login -u AWS -p AQECAHj6lc4XIJw/7ln0Hc00DMek6GExHCbY4RIpTMCI58InUwAAAw0wggMJBgkqhkiG9w0BBwagggL6MIIC9gIBADCCAu8GCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM5LqPfl7wxwIbg1CSAgEQgIICwHm4y7djbW2ExtX6GaAEYUH6rsJ+nJIzv71Th7jz0x3Z2mxR5JlcaZvnmTR81a3qUzmRi0pERveDRcnjYykEu/dW1q+HqODTt9SYhZksu4GWxFI2l12FuXaVf2O4xuyiJTpcIwdpDQIq5E6Vvm8rDYxpjNO0zQk9bHweRBATrp/OArShpapLP+k9wfLVo7THZ1aOUr8iG2+JtrhB4h9APJcdAE03gIHONGYMIH90NvQwtrdITY2X1k7rAqazxw8SeEXEM9HtvmZIPMaONOxBBuI5+bN7zqgzJnBc1JJ3LCGM25eU3t3LXYwZktMesReHbQVLgaRGMMicmtjeq+AZWZr+AgwZkEtW4j4D90V7t9Nur7Xc+x134/wB3OF/oB9J/RocEJ41AD1sopiyO4j71g1m0jIZTnH0se8kgIMT0Gjd/XiGxigLZGVS5y30jpeovD3jT3f4GzU3bv1e6yEQYztGr8bx0IfsQVAzv0d4nlnasjp1nw9VFxVv9F9VEoxoFMoC0rZQlm4grtwD1IYjhegv9mr+M+PW2ZvIIxBEsOlv9FnqDp4Q2Hmijoy+yU/mMMXbBEop7thASADAsyyNeaa/J6APysjI+tybDJH6QFGKw83US+irqkFlncOPW39uCzYmaVz+lir4JPIpmlwAM4M9jQyi+h9tOvbct2Q4risz5vj2vGNJw7RNAcluW914Kfn/sVCyAh2wjXxhG14o8Q0gfU1PPVPItJiFLsKEcl884M5ioM/pKeQkFEtIjFLPkcPOjha3VQgOwFOF0am8RQ0bDYC4sL1yQtUo9/KJVSJB2GPyjHx96QwXJH0nO7D/2BO0mpwY0yC4K2+pcFYzGlE9hbMviuwhhUCI5zB8wMK/k3ZgthAl7vSnFaTu/2B+b81zeKQuZ0+YCfA9/pLf+Q4jDVPzo9sN32AKVREOYVLe -e none https://038978466642.dkr.ecr.us-west-2.amazonaws.com
    - docker tag coursecorrect:latest 038978466642.dkr.ecr.us-west-2.amazonaws.com/coursecorrect:latest
    - docker push 038978466642.dkr.ecr.us-west-2.amazonaws.com/coursecorrect:latest
