stages:
  - build
#  - test
  - deploy

#services:
  #- docker:dind
  #- cgswong/aws

build-go:
  stage: build
  image: golang:1.7
  tags:
    - build
  before_script:
      - mkdir -p /go/src/27thisotope.ddns.net/mibzman/
      - cp -r /builds/mibzman/CourseCorrect-Student /go/src/27thisotope.ddns.net/mibzman/
      - mkdir -p /go/bin
      - curl https://glide.sh/get | sh
      - cd /go/src/27thisotope.ddns.net/mibzman/CourseCorrect-Student
      - glide -v
      - glide install
  artifacts:
    paths:
       - CourseCorrect-Student
       - Dockerfile
  script:
    - go build
    - mv CourseCorrect-Student /builds/mibzman/CourseCorrect-Student

#test-my-project:
#  stage: test
#  script:
#    - go test

deploy-backend:
  stage: deploy
  #image: cgswong/aws
  only: #makes the deploy only happen on master
    - master
  environment:
    name: production
    url: path-finder.ddns.net
  before_script:
    - pwd
    - ls
    # do nothing to override the global one
  dependencies:
  - build-go
  tags:
    - deploy
  script:
    - ls
    - aws ecr get-login --region us-west-2 | sh
    - docker build -t pathfinder-frontend .
    - docker tag pathfinder-frontend:latest 038978466642.dkr.ecr.us-west-2.amazonaws.com/pathfinder-frontend:latest
    - docker push 038978466642.dkr.ecr.us-west-2.amazonaws.com/pathfinder-frontend:latest

    - docker build -t pathfinder-frontend frontend/
    - docker tag coursecorrect:latest 038978466642.dkr.ecr.us-west-2.amazonaws.com/coursecorrect:latest
    - docker push 038978466642.dkr.ecr.us-west-2.amazonaws.com/coursecorrect:latest
