before_script:
  script:
    - ls
    - mkdir -p /go/src/27thisotope.ddns.net/mibzman/CourseCorrect-Student
    - mkdir -p /go/bin
    - curl https://glide.sh/get | sh
    - cd /go/src/27thisotope.ddns.net/mibzman/CourseCorrect-Student
    - glide -v

stages:
  - build
  - test

build-my-project:
  stage: build
  script:
    - glide install
    - go build

test-my-project:
  stage: test
  script:
    - cd CourseCorrect-Student
    - go test
