
stages:
  - setup
  - build
  - test

setup-my-project:
  stage: setup
  script:
    - mkdir -p /go/src/27thisotope.ddns.net/
    - cd go/src/27thisotope.ddns.net/mibzman/

build-my-project:
  stage: build
  script:
    - cd CourseCorrect-Student
    - go get -d
    - go build

test-my-project:
  stage: test
  script:
    - cd CourseCorrect-Student
    - go test