stages:
  - install-environment
  - build
  - test

setup-my-project:
  stage: install-environment
  script:
    - mkdir -p /go/src/27thisotope.ddns.net/mibzman/
    - cd /go/src/27thisotope.ddns.net/mibzman/

build-my-project:
  stage: build
  script:
    - ls
    - cd CourseCorrect-Student
    - go get -d
    - go build

test-my-project:
  stage: test
  script:
    - cd CourseCorrect-Student
    - go test